### ISSUE TITLE
Fanart1 to FanartX is ignored

### ISSUE THREAD

**Issue by Canuma** [malvinas2/skin.titan.vanilla#6]
With Artworkbeef and kodi 18, there is new(?) Fanart Artwork, fanart1 to fanartX. Unfortunately, all of the Titan incarnations seems to ignore that. I do not have extrafanart, but i do have fanart1 to x. (Not in the data path though, so it has to be pulled from the database)
I would fix that myself, but honestly i am still not so deep into titan or skinning at all.
Hope you can help

**Comment by malvinas2** [comment]
According to the description [https://forum.kodi.tv/showthread.php?tid=341179](https://forum.kodi.tv/showthread.php?tid=341179) extended artwork and extra fanart should be working using additional tags in advancedsettings.xml out of the box, without the help of addons like Artwork Beef etc. This is not implemented in the current version of Titan and I don't know of any skin which can serve as a kind of 'reference implementation'. And as you recognized this means massive changes to the skin. So this will be done in a V19 version, but not in the actual one. Till then you have got to use the extrafanart solution, sorry.

**Comment by malvinas2** [comment]
Will be supported within the next update of V20 resp. V21.
